name: Build Docker Images

on:
  pull_request:
    branches:
      - main
      - release/*
  push:
    branches:
      - main
      - release/*
  release:
    types:
      - created

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@v1.2.0
    with:
      image-name: hades-scheduler/hades/junit-result-parser
      docker-file: ./Dockerfile
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=raw,value=latest,enable={{is_default_branch}}
    secrets: inherit
